### PR TITLE
Implement hashtag tracking.

### PR DESCRIPTION
**Pull request by brenns10**
It's basically like the fuck count tracking, except with hashtags.  Also, I used pure Javascript, just to demonstrate that you don't have to use Coffeescript!

Implements #37.

### CODE REVIEW

**Comment by brenns10** [comment]
@thomasrussellmurphy any comments on this guy?

**Comment by thomasrussellmurphy** [comment]
Updates to the documentation?

**Comment by brenns10** [comment]
That's on the `gh-pages` branch, so it can't be done in the same PR.  I generally just run the script to update docs after I merge.

**Comment by thomasrussellmurphy** [comment]
Ah, very good. If you've tested this rather preferable JS, go for it.

**Comment by brenns10** [comment]
It is indeed tested.

**Pull request merged**
