### PR TITLE
Added script to track the number of fucks said by each user.

### PR DESCRIPTION
**Pull request by brenns10**
This is right up there on the list of reasons not to code after 1AM.

I made a script for hubot that counts the number of times each user uses the word "fuck."  I'm not sure how acceptable this kind of content is, but judging by my time on irc.case.edu, it'll probably fit right in :)

### CODE REVIEW

**Comment by thomasrussellmurphy** [comment]
No newline at EOF. #nitpickthings

**Comment by brenns10** [comment]
Shall I `s/said/given/g` ?

**Comment by thomasrussellmurphy** [comment]
+1 to @ajm188's suggestion of `(said|given)`.

**Comment by brenns10** [comment]
Tada, bitches.

**Pull request merged**
