### PR TITLE
Getting a different version of roles.coffee

### PR DESCRIPTION
**Pull request by thomasrussellmurphy**
Acquired from https://github.com/ropensci/hubot/blob/master/scripts/roles.coffee and it appears to do something in interactive hubot.
Not sure if this is substantially better, but we can try. This script appears not to be available in an official location.

### CODE REVIEW

**Comment by brenns10** [comment]
Give it a shot?

**Comment by brenns10** [comment]
Test in production?

**Comment by thomasrussellmurphy** [comment]
Test in prod aye. Merging now.

**Comment by thomasrussellmurphy** [comment]
Operates. . . As expected. Deleting branch.

**Pull request merged**
