### PR TITLE
Lulu brain

### PR DESCRIPTION
**Pull request by brenns10**
I believe this would implement #14.  Just need to send the REDIS_URL string to @thomasrussellmurphy.

### CODE REVIEW

**Comment by thomasrussellmurphy** [comment]
Have you tested connecting to redis?

**Comment by brenns10** [comment]
Yes I have, using the REDIS_URL I gave you.  State (well, fucks and roles were all I checked) persisted across multiple runs of hubot.

**Comment by thomasrussellmurphy** [comment]
+1, to prod with it.

**Comment by brenns10** [comment]
Wait, hold up, bug

**Comment by brenns10** [comment]
Let me fix it real quick.

**Comment by thomasrussellmurphy** [comment]
Very well.

**Comment by brenns10** [comment]
Now we're good. Shall we :shipit:?

**Comment by thomasrussellmurphy** [comment]
If things are good, :ship: may sail.

**Pull request merged**
