### PR TITLE
Implemented Marco-Polo command.

### PR DESCRIPTION
**Pull request by brenns10**
This would implement #12.

### CODE REVIEW

**Comment by brenns10** [comment]
I've tested this just as much as I've tested my `O(n)` solution to the halting problem, so I vote test in prod.

**Comment by thomasrussellmurphy** [comment]
Local testing fails. Please check implementation and update the documentation comment.

**Comment by brenns10** [comment]
I updated the documentation comment, but testing worked fine for me:

```
Hubot> hubot ping
undefined!
PONG
Hubot> hubot marco
undefined!
Polo!
Hubot>
```

Are you sure you pulled and checked out my branch?

**Comment by thomasrussellmurphy** [comment]
Did have the correct branch, did not type things right. My bad. Cleared to merge.

**Comment by brenns10** [comment]
The downside is that whenever this is put into production, many karma and associations will be deleted.

**Pull request merged**
