### PR TITLE
Help link

### LINKED ISSUE #17: incomplete help text
doing a query against lulu with "lulu help", or, more preferably "/msg lulu help", produces an instant flood of returned text.

lulu is likely hitting the IRC's preconfigured flood limit, and being cut off.

This could also explain why lulu sometimes doesn't provide URL about text for links sometimes.

### PR DESCRIPTION
**Pull request by brenns10**
This would fix #17 (mostly).  You could still get lulu to respond back by doing something like `lulu help .`.   But for the most part, if you just ask `lulu help`, it should send you a link to a new markdown file containing commands.  Without flooding the server.

### CODE REVIEW

**Comment by brenns10** [comment]
It doesn't look like I really articulated what this PR is for.  Currently, if you ask Lulu for help, it responds in a query with a flood of messages that get delayed to like one per second.  It's infuriating.  So, this pull request makes Lulu send back a link to a newly created file on this repo for a list of commands, instead of the previous behavior.  Lulu will still reply with help on a command if you specify which command you want help on -- this only affects the behavior when you simply ask `lulu help` with no command name.

However, it's not a silver bullet.  The way I'm currently doing it just checks whether you provide a command name after `lulu help`.  "Since the help command uses regex matching, if you did a command like `lulu help .*`, you'd still get back a flood of messages.  I could instead limit by the number of matches (say, after 5 lulu just sends a link to the repository).  But practically, I think this approach is fine, and will avoid unpleasant trickle flow-rate help messages from unsuspecting lulu first-timers.

**Comment by thomasrussellmurphy** [comment]
Looks useful! Is it possible to automate updating the command listing?

**Comment by brenns10** [comment]
Not any easy automatic way.  I suppose I could write a shell script for that.  Something along the lines of `echo "hubot help .*" | bin/hubot > commands.md`.  And hey, then I could set up Travis to run that on every commit to master.  But that seems like overkill.

**Comment by brenns10** [comment]
However, Hubot does supposedly have a HTTP listener, and our help script can serve help pages.  If we were to enable that, Hubot could just link to something like `http://irc.case.edu:8000/lulu/help` or something like that.

**Comment by thomasrussellmurphy** [comment]
Currently we operate lulu with the `--disable-httpd` option, probably for security, since irc.case.edu is a publicly accessible site. Perhaps use the GitHub Pages for this repository to host such a document?

**Comment by brenns10** [comment]
So, I have created a `gh-pages` branch, and created a script that will (on my computer) update the command listing automatically (well, with a 15 second sleep).  It's kinda really janky.  But it works.

**Comment by thomasrussellmurphy** [comment]
Sounds like good stuff.

**Comment by brenns10** [comment]
I'm going to merge this.  It works on two of my computers.  For the record, you'll need to have the `expect` program to run this.  Also, I believe you need to have GNU coreutils in order for my script to work, since I'm probably using some GNU extensions.  Make sure you have the `gh-pages` branch fetched also before you run it.  The script takes like 15 - 20 seconds to run (due to some sleep synchronization).

It's probably best that, whenever you merge a pull request that may add changes or documentation, run the script and push directly to `gh-pages` to update the documentation.

**Comment by thomasrussellmurphy** [comment]
Deployed successfully, thanks!

**Pull request merged**
