### PR TITLE
Update web.coffee

### PR DESCRIPTION
**Pull request by raidancampbell**
update to default 200 characters
- accept environment variable `HUBOT_WEB_TITLE_LEN`
- conditional ellipsis
- untested

### CODE REVIEW

**Comment by thomasrussellmurphy** [comment]
Please add the environment variable to https://github.com/hacsoc/lulu/blob/master/README.md#expected-environment-variables as an `(optional parameter)`.

**Comment by raidancampbell** [comment]
not until it's tested as working

**Comment by thomasrussellmurphy** [comment]
Tested in prod.

**Comment by brenns10** [comment]
Lol what even are unit tests?

**Comment by thomasrussellmurphy** [comment]
What even is "functional dev environment".

**Comment by raidancampbell** [comment]
for reference, I'm just writing all this code in the github text editor, so I have no clue if there's syntax errors

**Comment by thomasrussellmurphy** [comment]
So far, it's gone swimmingly and lulu is happily deployed with more features.

**Comment by brenns10** [comment]
@raidancampbell I mean considering that you normally use nano, the github text editor has to be a major upgrade

**Comment by raidancampbell** [comment]
@brenns10 I mean considering that you normally use emacs, you could browse github in emacs to experience the built-in text editor

**Pull request merged**
