### PR TITLE
Add useful scripts

### PR DESCRIPTION
**Pull request by thomasrussellmurphy**
I sure hope these work right.

### CODE REVIEW

**Comment by brenns10** [comment]
Did you test?

**Comment by thomasrussellmurphy** [comment]
Just about not.

**Comment by brenns10** [comment]
:-1:

**Comment by thomasrussellmurphy** [comment]
Best way to actually test this not in prod?

**Comment by timtadh** [comment]
i mean it is a hubot instance... not exactly a mission critical app. @thomasrussellmurphy deploy and see if works.

**Comment by thomasrussellmurphy** [comment]
Merging and doing it live.

**Comment by brenns10** [comment]
Although, for future reference:

```
npm install
bin/hubot
```

Works. A few error messages but you can test your additions nonetheless.

**Pull request merged**
