### PR TITLE
Make packages current, enable local development

### LINKED ISSUE #34: Consider updating jsdom once io.js returns to node.js
Since `io.js` will be merging back into `node.js` in the not-too-distant-future, we can expect that `jsdom` will become compatible with hubot run on node.js, so the version restriction in `package.json` could be lifted.

I will vaguely monitor the situation. See the merger at https://github.com/nodejs/node

### LINKED ISSUE #49: Functional Dev Environment with Latest NPM packages
Testing in dev? Let's see about that. Currently, running locally with the latest material is a terrible experience that doesn't work.

### PR DESCRIPTION
**Pull request by thomasrussellmurphy**
Dug through everything to get it running on my machine with the latest packages given by `npm install`.

If working correctly, this closes #34 and closes #49.

### CODE REVIEW

**Comment by brenns10** [comment]
works on my machine ++ :shipit:

**Comment by raidancampbell** [comment]
@thomasrussellmurphy told me I should approve this for merging.  I haven't looked at the code.

+1 for merging.

**Comment by thomasrussellmurphy** [comment]
And deployed. Required `sudo npm install n -g` `sudo n stable` to convince `nodejs` to be updated.

**Comment by thomasrussellmurphy** [comment]
Yeah, basically. Thanks, Javascript development requirements.

**Pull request merged**
